# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags
notifications:
  email: false
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 0.7 ]]; then
      julia --project -e 'using Pkg; pkg"add Coverage"; using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
jobs:
  include:
    - stage: Documentation
      julia: 0.7
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip